### ISSUE TITLE
selector grammer not work when the selector element is lazy-loaded

### ISSUE THREAD

**Issue by imageslr** [imageslr/chrome-tab-modifier#1]
https://github.com/imageslr/chrome-tab-modifier/commit/aab6a43bd9f932873758a8f8cae389b37341375f#commitcomment-47379301

**Comment by imageslr** [comment]
Please try the newest commit: https://github.com/imageslr/chrome-tab-modifier/commit/a2bae00d7b5f87ac38c493b4a0a367cb0ef7dd96

@dnknn

**Comment by dnknn** [comment]
@imageslr  I want to ask, how to use repo,  

	You can load unpacked extension in project `/dist` folder. ?
	
	
The test results seem to be perfect, and now the CSS selector can be worked normally!
