### ISSUE TITLE
add a column to the rule list on the options page

### ISSUE THREAD

**Issue by imageslr** [imageslr/chrome-tab-modifier#2]
https://github.com/imageslr/chrome-tab-modifier/commit/aab6a43bd9f932873758a8f8cae389b37341375f#commitcomment-47381391

> ON/OFF : Pause/Disable. But not delete, It’s a very useful function. Sometimes we want to pause/don’t want to display the custom title temporarily. It can even be said to be because of a bug, like the {css} invalid bug I proposed. If there is a pause switch, I click Just pause! You don't have to delete it.

**Comment by imageslr** [comment]
Hi @dnknn, I have added this feature. Please try it!

**Comment by dnknn** [comment]
OK, Thank you very much!
