### ISSUE TITLE
Allow to hide right click item

### ISSUE THREAD

**Issue by imageslr** [imageslr/chrome-tab-modifier#4]

**Comment by imageslr** [comment]
Hi @dnknn, please try it out. If there are any bugs, please let me know. Thank you!

![image](https://user-images.githubusercontent.com/17822028/108724479-54814400-7560-11eb-926d-8a0a26c42fc6.png)

**Comment by dnknn** [comment]
@imageslr Great!  The test works normally!

But the right click menu is invalid, this is a bug, Right-click on the source version can work.

It’s just a pity that you can’t reproduce it.

**Comment by imageslr** [comment]
Right-click not working might be the bug caused by my modification. I will try it on another computer someday.

**Comment by dnknn** [comment]
> I will try it on another computer someday.

Well, don't worry, just remember!

by the way,   about `OneTab`extension, I recommend you to use this :

**better-onetab**  (The function is much more powerful!)
https://chrome.google.com/webstore/detail/eookhngofldnbnidjlbkeecljkfpmfpg
https://github.com/cnwangjie/better-onetab

**Comment by imageslr** [comment]
Thank you for your recommendation. BetterOneTab is awesome and very useful for me.

**Comment by dnknn** [comment]
> BetterOneTab is awesome and very useful for me.

BetterOneTab it can support for selected/`highlighted` multiple tabs with holding `Ctrl/Shift/Ctrl+Shift`
