### ISSUE TITLE
right-click menu item not working in windows 10, Chrome/Chromium86 (CentBrowser.com) 

### ISSUE THREAD

**Issue by imageslr** [imageslr/chrome-tab-modifier#5]
Is only the right-click menu item not working? Or right-click and tray icon both? @dnknn

**Comment by dnknn** [comment]
> Or right-click and tray icon both?

Yes, **both** .
 Because these two are exactly the same function

**Comment by imageslr** [comment]
What's your meaning of not working? Is there no prompt at all when you clicked menu item or right-clicking tray-icon?

I have installed the centbrowser but it works fine for me.

* Browser version: 版本 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)
* OS version: Windows 10 19042.631

![Kapture 2021-02-22 at 23 29 10](https://user-images.githubusercontent.com/17822028/108729738-cad47500-7565-11eb-8cc3-1565ce7a1e50.gif)

**Comment by dnknn** [comment]
> Is there no prompt at all when you clicked menu item or right-clicking tray-icon?

yes!

**Comment by imageslr** [comment]
Hi, what's your browser version? 

Have you try to install this forked extension in a fresh new environment? ---- Update the browser, and sign in a new account or disabled all extensions, then reinstall this extension. I guess it might be conflict with another extension. (just guess :)

**Comment by dnknn** [comment]
> I guess it might be conflict with another extension. (just guess :)

no, I know the reason,  But still weird...

- If you download [the `dist` folder](https://github.com/imageslr/chrome-tab-modifier/tree/master/dist) of the repo separately to Install , 
　　Will generate another extension 🆔, there is no problem.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/10995302/108739348-877f0400-756f-11eb-8a8a-0fc1a27c571a.png)

</details>


----

- Here is my usage: (right-click menu invalid problem)

1. Install the original author's store version
　　https://chrome.google.com/webstore/detail/hcbgadmbdkiilgpifjgcakjehmafcjai
　　🆔 is `hcbgadmbdkiilgpifjgcakjehmafcjai`

![image](https://user-images.githubusercontent.com/10995302/108735571-af6c6880-756b-11eb-89d5-dfed51b1f6a5.png)
CentBrowser can directly modify the local files of the extension (i.e. it removes the store verification of the extension)

2. Clear all files (folders) in the directory above 👆.

3. download [the `dist` folder](https://github.com/imageslr/chrome-tab-modifier/tree/master/dist) of the your repo to `Ctrl+V` 👆

4. Bug : right-click menu invalid problem

**Comment by dnknn** [comment]
CentBrowser can directly modify the local files of the extension (i.e. it removes the store verification of the extension)

**Comment by dnknn** [comment]
Portable version 👇
http://centbrowser.com/history.html

![image](https://user-images.githubusercontent.com/10995302/108737417-8cdb4f00-756d-11eb-9c3a-43ede1f4ccc2.png)

**Comment by imageslr** [comment]
Oh I see. I have tried but I don't why. Replacing an existing extension's file is not a regulary way. 

Have you tried to load through "load unpacked file" in developer mode? Is there still the problem?

**Comment by dnknn** [comment]
> Have you tried to load through "load unpacked file" in developer mode? Is there still the problem?

Tested, no problem.


> Oh I see. I have tried but I don't why. Replacing an existing extension's file is not a regulary way.

But the problem is: if you don’t do that, it means to give up the https://chrome.google.com/webstore/detail/hcbgadmbdkiilgpifjgcakjehmafcjai version ?

It is estimated that the original author has abandoned the project, or I just use your repo version?

https://download-directory.github.io/?url=https://github.com/imageslr/chrome-tab-modifier/tree/master/dist

What is your opinion?

**Comment by imageslr** [comment]
Every extension has an unique ID which binds to its source files and runtime states. So simply replacing local files might cause problem due to the inconsistency of the internal state. 

Please use my forked version by loading dist directory. They are two different package From Chrome's view. Remember to export your rules first from the origin author's version and then import it in new version. 

I will publishing a public package on Chrome web store. It's under review now. I'll let you know!

**Comment by dnknn** [comment]
> I will publishing a public package on Chrome web store. It's under review now. I'll let you know!

💪👍 It’s so pretty, so I don’t have to maintain the version manually !!! 

I will wait for your good news!

**Comment by imageslr** [comment]
I can also make a PR to the origin repo. But that depends on the author to decide accept or not.

**Comment by dnknn** [comment]
> I can also make a PR to the origin repo. But that depends on the author to decide accept or not.

I just install your chrome.google.com/webstore/detail/ version, the original author has given up to continue maintenance.

<details>
<summary>Title</summary>

![image](https://user-images.githubusercontent.com/10995302/108744712-396cff00-7575-11eb-84d8-8f1620c3cb5d.png)
</details>

**Comment by dnknn** [comment]
Hi @imageslr I would like to ask whether it was successfully published in the Chrome web store?
> > I will publishing a public package on Chrome web store. It's under review now. I'll let you know!

**Comment by imageslr** [comment]
Hi @dnknn I'm regularly checking it and it's finally public now! Please see [Chrome webstore](https://chrome.google.com/webstore/detail/tab-renamer/kpijejpdbpeaakidlcopnbjohbfimnod).

**Comment by dnknn** [comment]
Very great! Thank you very much!!!

**Comment by dnknn** [comment]
@imageslr 
https://github.com/imageslr/chrome-tab-modifier
You should also add a link to the [Chrome webstore](https://chrome.google.com/webstore/detail/kpijejpdbpeaakidlcopnbjohbfimnod) on this page so that users can discover it!

**Comment by imageslr** [comment]
Oh I forgot it. Thanks for you notification!
